bp/resqpy

.gitignore
resqpy/derived_model.py

fix of bug affecting split pillar data when adding a fault that intersects an existing fault

add_faults() bug fix for new fault intersecting existing fault

---

resqpy/derived_model.py
resqpy/grid.py
tests/test_fault_connection_set.py

This change completely re-works the fault throw scaling function in the derived_model module. This function was not working property where faults intersected one another.
The creation of the column-pillar mapping in the Grid module has also been rewritten.

WIP: Cross fault bug fix

---

README.md
docs/CONTRIBUTING.rst
docs/index.rst

Can be previewed here:
https://resqpy.readthedocs.io/en/dev-docs/
Nb. link above takes several minutes to reflect most recent commit.

Improved documentation

---

.github/workflows/ci-tests.yml

Change pytest coverage to use editable install

---

resqpy/well.py

Added convenience function to quickly create wellbore interpretation and wellbore feature objects for a blocked well object. 
Other minor bug fixes.

Blocked well add interpretation and feature convenience

---

resqpy/lines.py
resqpy/surface.py
resqpy/well.py
tests/conftest.py
tests/test_lines.py
tests/test_surface.py
tests/test_well.py

New convenience functions for wellboremarkerframe and trajectory, to allow easy adding of wellboreinterpretation and wellborefeature objects.

New convenience functions to add wellboreinterp and feature 

---

resqpy/surface.py

Small change to allow hdf5 file name and ext uuid to be defaulted in PointSet methods write_hdf5() and create_xml()

Point set write hdf5

---

resqpy/crs.py
resqpy/fault.py
resqpy/grid.py
resqpy/grid_surface.py
resqpy/lines.py
resqpy/model.py
resqpy/property.py
resqpy/surface.py
resqpy/time_series.py
resqpy/well.py

This change adds meta common lines to the docstrings for the more commonly used methods of large classes. This results in a separate grouping in readthedocs.

addition of meta common indicators to docstrings, issue #34

---

docs/getting-started.rst
docs/tutorial/getting_started_with_model.rst
docs/tutorial/grid_properties.rst
docs/tutorial/high_level_objects.rst
docs/tutorial/intro_to_resqml.rst
docs/tutorial/tutorial_index.rst
docs/tutorial/working_with_coord.rst
resqpy/crs.py

Mostly minor changes to existing tutorials

changes to tutorial docs

---

resqpy/derived_model.py
resqpy/grid_surface.py
resqpy/lines.py
resqpy/olio/rq_print.py
resqpy/rq_import.py
resqpy/surface.py
resqpy/well.py

This change modifies calls to the Crs() instantiation method to use uuid instead of root. The exception is Trajectory which would require more significant changes, including in calling apps.

switch to using uuid when instantiating Crs (except for Trajectory)

---

resqpy/organize.py
resqpy/well.py
tests/test_organize.py
tests/test_well.py

Add IO tests for resqpy.organise and resqpy.well objects

---

resqpy/olio/weights_and_measures.py
tests/test_wam.py

volume flow rate conversion function added to olio.weights_and_measures

---

resqpy/lines.py
resqpy/model.py
resqpy/organize.py
resqpy/surface.py
resqpy/well.py
tests/test_lines.py
tests/test_surface.py

Updates to prefer uuids rather than parts or roots

---

resqpy/derived_model.py
resqpy/lines.py
tests/test_fault_connection_set.py

This change adds another option to the source of lines in the derived_model.add_faults() function: a polylines argument may be passed, either being a lines.PolylineSet or a list of lines.Polyline.
resolves issue #63

enhancement to derived_model.add_faults(); resolves #63

---

resqpy/crs.py
resqpy/olio/base.py
resqpy/olio/consolidation.py
resqpy/olio/dataframe.py
resqpy/olio/rq_print.py
resqpy/organize.py
resqpy/property.py
resqpy/rq_import.py
resqpy/time_series.py
tests/test_crs.py
tests/test_property.py
tests/test_timeseries.py

The Crs class has already had some reuse functionality updated.
Closes #79

base and reuse workover of StringLookup, PropertyKind, TimeSeries & Crs classes

---

resqpy/model.py
tests/test_model.py

Add model.iter_obj method and unit test

---

docs/CONTRIBUTING.rst
resqpy/model.py
tests/test_model.py

Closes #22
Example of resulting graph, plotted with networkx and holoviews:

Add method to export model as a graph

---

resqpy/grid.py
resqpy/olio/base.py
resqpy/olio/xml_et.py
resqpy/property.py
tests/test_base.py
tests/test_property.py

This change introduces a Property class which sits alongside PropertyCollection but behaves more like other resqpy classes. It aims to be easier to use than PropertyCollection when calling code is only interested in one property at a time.

Initial code for Property class

---

resqpy/derived_model.py
resqpy/fault.py
resqpy/grid.py
resqpy/grid_surface.py
resqpy/model.py
resqpy/olio/transmission.py
resqpy/property.py
tests/test_surface.py

This change brings the resqpy GridConnectionSet class in line with others inheriting from BaseResqpy

Changes to fault.py (GridConnectionSet) to use BaseResqpy and uuid; closes #104

---

resqpy/derived_model.py

extra_metadata arg added to derived model functions that add properties

---

resqpy/property.py
tests/test_property.py

Property class loading extra metadata from collection

---

resqpy/lines.py
tests/test_fault_connection_set.py
tests/test_lines.py

switching lines classes to use BaseResqpy and prefer uuid

---

resqpy/crs.py
resqpy/fault.py
resqpy/grid.py
resqpy/lines.py
resqpy/olio/base.py
resqpy/olio/rq_print.py
resqpy/organize.py
resqpy/property.py
resqpy/surface.py
resqpy/time_series.py
resqpy/well.py

Also, load_from_xml now underscored (ie. private, only called from BaseResqpy's init method)
Closes #117

well classes given BaseResqpy and uuid treatment

---

resqpy/well.py

docstrings for init methods in well.py updated with originator and extra_metadata args

well.py docstring update

---

resqpy/well.py

there were 2 bugs relating to dependant part creation (MdDatum and Trajectory) for blocked wells

bug fixes for blocked well create_xml

---

resqpy/well.py

Oops, I accidentally pushed direct to master. This pull request is to ensure some audit trail and trigger the pipeline.

removing case_sensitive_units argument

---

resqpy/fault.py

This change is needed to fix a bug affecting the use of layer ranges in the handling of grid connection sets by some of the wrapper functions. The proposed fix enhances the functionality of the grid connection set filtering methods to give the option of keeping the filtered feature indices compatible with the original (unfiltered) ones.

adding pare_down argument to grid connection set filtering methods

---

resqpy/well.py

This change fixes a bug in the well.Trajectory.xyz_for_md() that was causing a crash in particular circumstances when the measured depth was at the finish md of the trajectory.

correcting bug in method for locating xyz for md in Trajectory

---

resqpy/grid.py
resqpy/grid_surface.py
resqpy/model.py
resqpy/olio/ab_toolbox.py
resqpy/olio/factors.py
resqpy/olio/keyword_files.py
resqpy/olio/load_data.py
resqpy/olio/point_inclusion.py
resqpy/olio/rq_print.py
resqpy/olio/simple_lines.py
resqpy/olio/vdb.py
resqpy/olio/wellspec_keywords.py
resqpy/olio/write_data.py
resqpy/olio/write_hdf5.py
resqpy/olio/xml_et.py
resqpy/olio/zmap_reader.py
resqpy/property.py
resqpy/rq_import.py
resqpy/surface.py
resqpy/time_series.py
resqpy/well.py
setup.cfg
tests/test_s_bend.py
tests/test_transmission.py

As per our offline discussion, adding a few more "E-numbers" for the relatively more important style checks, and making some simple fixes accordingly until the linter passes.
Related: #114

Remove bare "Except" statements, and rename ambiguous variables

---

resqpy/well.py

a small change to encourage consistent citation titles for a family of well objects

removes blocked well title suffix

---

resqpy/well.py

removes use of anglv & angla in determination of entry & exit points for blocked well trajectory
this is a simplification due to NaNs sometimes appearing when using the vector intersection approach (which has other fundamental issues anyway)

blocked well trajectory NaN bug fix

---

resqpy/olio/base.py
tests/test_well.py

This request is for changes needed to improve the intersection of simulation trajectories with a refined grid (LGR).
- commented out a couple of debug statements in base.py

attempt to resolve issues with blocked well refinement

---

docs/tutorial/working_with_coord.rst

Correcting an error spotted by Kadija.

blank line added to correct markup in crs tutorial

---

resqpy/crs.py
resqpy/derived_model.py
resqpy/grid_surface.py
resqpy/lines.py
resqpy/model.py
resqpy/well.py
tests/conftest.py

The main focus of changes are in the well module. However, the model and lines modules have also been modified in a similar way.

replacing some secondary root reference attributes with uuids

---

resqpy/olio/dataframe.py
tests/test_dataframe.py

adds uuid arg to initialisation methods for DataFrame and TimeTable

---

resqpy/model.py
resqpy/olio/xml_et.py

adding option to cut references to given uuids during copy part from other model

Option to cut references to given uuids during copy

---

resqpy/well.py

only calling self.model.grid() when needed during blocked well initialisation

fix of bug affecting initialisation of empty BlockedWell in multi-grid model

---

resqpy/lines.py
resqpy/olio/base.py
resqpy/property.py
resqpy/surface.py
tests/test_base.py

Adding extra_metadata saving and reading to PointSetRepresentation

Add extra_metadata to pointset

---

resqpy/grid.py

correction of inactive line bug in grid.py; resolves #183

---

docs/CONTRIBUTING.rst

Following up discussion in #181

Add info to CONTRIBUTING about previewing online docs

---

docs/tutorial/cellular_grids.rst
resqpy/__init__.py
resqpy/unstructured.py

also some unstructured notes in _cellular grids_ tutorial

Including unstructured module in sphinx documentation

---

resqpy/olio/triangulation.py
resqpy/olio/vector_utilities.py
resqpy/olio/volume.py
resqpy/unstructured.py
tests/test_unstructured.py
tests/test_volume.py

This change adds functionality to the classes in the unstructured module.

new methods for UnstructuredGrid and derived classes

---

resqpy/olio/vector_utilities.py
resqpy/unstructured.py
tests/test_unstructured.py

- syntax bug fix affecting UnstructuredGrid.centre_point() when called for a single cell

fix for bug in unstructured grid code found during inter-operability tests

---

resqpy/property.py
resqpy/surface.py
resqpy/unstructured.py
tests/test_surface.py
tests/test_unstructured.py

This change adds a VerticalPrismGrid class, inheriting from PrismGrid. A class method allows construction of such a grid from a list of surfaces.

WIP: Prism grid from surfaces

---

resqpy/property.py
tests/test_property.py

adds support for 'nodes' and 'nodes per cell' indexable elements for IJK grid properties
resolves issue #211

adds support for 'nodes' and 'nodes per cell' indexable elements; closes #211

---

docs/tutorial/high_level_objects.rst
resqpy/derived_model.py
resqpy/grid.py
resqpy/model.py
resqpy/property.py
resqpy/time_series.py
tests/test_property.py
tests/test_s_bend.py
tests/test_strata.py
tests/test_timeseries.py

This change adds support for the RESQML class obj_PointsProperty.

code for points properties; resolves issue #212

---

resqpy/derived_model.py
resqpy/grid.py
resqpy/well.py
tests/test_derived_model.py

Also fix of bug affecting add_zone_by_layer_property() when 'zone' local property kind does not pre-exist.

some tests for derived_model functions

---

resqpy/grid.py
tests/test_property.py

Initial code changes made, not yet tested
Resolves issue #230

WIP: enhancement to Grid to support geometry time index info; see issue #230

---

resqpy/grid.py
resqpy/property.py
tests/test_property.py

This change adds the option to expand constant property arrays to full arrays when writing to hdf5 and creating xml.
Affected classes are:
- PropertyCollection
- Property
- Grid
- RegularGrid
Resolves issue #210

optional expansion of constant property arrays; resolves issue #210

---

resqpy/lines.py
resqpy/olio/point_inclusion.py
resqpy/olio/triangulation.py
resqpy/olio/vector_utilities.py
tests/test_lines.py
tests/test_point_inclusion.py
tests/test_triangulation.py
tests/test_vector_utilities.py

This change builds on the Delauney triangulation functionality to compute the dual Voronoi diagram (in 2D).  This could be used, for example, to define polygons around well locations where all points within a polygon are closer to the seed well than any other well.

Voronoi diagram from Delauney triangulation

---

resqpy/property.py
tests/conftest.py
tests/test_property.py

Initial tests to cover most of the functionality prior to any refactoring.

Integration - property.py - Initial integration and unit tests for property.py

---

resqpy/derived_model/__init__.py
resqpy/lines/__init__.py
resqpy/lines/_polyline.py
resqpy/strata/__init__.py
resqpy/unstructured/__init__.py

Closes #310
Discussion of the fix in the linked issue above

Fix docs for nested subpackages

---

resqpy/fault/__init__.py
resqpy/fault/_gcs_functions.py
resqpy/fault/_grid_connection_set.py
tests/test_fault.py

Refactoring of some GridConnectionSet methods

Fault workover

---

resqpy/derived_model/__init__.py
resqpy/organize/__init__.py
resqpy/property/__init__.py
resqpy/surface/__init__.py

module name override in remaining package inits

---

resqpy/lines/_common.py

Moving from double to single underscore usage in lines._common

Sunder lines

---

resqpy/olio/xml_et.py
tests/test_model.py

This change fixes a bug affecting the writing of xml strings containing any of the special characters & < >

bug fix affecting escape characters in xml; resolves issue #323

---

resqpy/olio/write_hdf5.py
resqpy/property/property.py
resqpy/property/property_collection.py
tests/test_write_hdf5.py

fix of bug affecting elemental type stored in hdf5 array when dtype in use

fix of bug affecting elemental type stored in hdf5 array

---

resqpy/property/__init__.py
resqpy/property/_collection_add_part.py
resqpy/property/_collection_create_xml.py
resqpy/property/_collection_get_attributes.py
resqpy/property/_collection_support.py
resqpy/property/grid_property_collection.py
resqpy/property/property.py
resqpy/property/property_collection.py
resqpy/property/property_common.py
resqpy/property/property_kind.py
resqpy/property/string_lookup.py
resqpy/property/well_interval_property.py
resqpy/property/well_interval_property_collection.py
resqpy/property/well_log.py
resqpy/property/well_log_collection.py
resqpy/rq_import/_add_surfaces.py

Remove deprecated call to crs_uuid in create_xml. This is now required at initialization stage (already in code)

Integration: add_surfaces bug - Remove deprecated call to crs_uuid

---

resqpy/property/property_collection.py
tests/conftest.py
tests/test_property.py

WIP: Refactoring - Additional tests and refactoring for remaining property classes

---

resqpy/property/_collection_create_xml.py
resqpy/property/_collection_get_attributes.py
resqpy/property/property_collection.py

Bug fix - updated handling of const arrays min/max values following refactoring

Updated handling of const arrays and min/max values

---

docs/CONTRIBUTING.rst

Emma, please merge this immediately if it looks okay to you

Adding Nirjhor and Andrew to list of contributors

---

tests/test_rq_import.py

Added test for _add_ab_properties.py in rq_import now that ab files are available in the test suite.

Tests - rq_import/_add_ab_properties.py 

---

tests/test_property.py

Single test to cover property collections with a grid2drepresentation as a support. Properties with indexable of cells and nodes added for testing.

Tests - Single additional test to cover properties on gridd2drepresentation objects

---

resqpy/organize/fault_interpretation.py
tests/test_fault_interpretation.py
tests/test_organize.py

Early PR to fix a bug introduced during the refactoring flagged by some new unittests

Unittests and Bugfix for Organize

---

docs/CONTRIBUTING.rst
resqpy/__init__.py

Changes can be previewed here:
https://resqpy.readthedocs.io/en/docs/CONTRIBUTING.html#making-a-release

Add info about setuptools_scm

---

resqpy/olio/triangulation.py

veronoi function refactored. Naming of inner functions need to be checked

veronoi function refactored

---

tests/unit_tests/conftest.py
tests/unit_tests/property/test_property.py

testing synonymity of rock permeability and permeability rock property kinds

testing synonymity of permeability property kinds; closes #329

---

resqpy/strata/__init__.py
resqpy/well/__init__.py

WIP: correcting well package init for docstring processing to readthedocs

---

resqpy/rq_import/__init__.py

adding post-amble to rq_import init for docstring processing

---

resqpy/fault/_grid_connection_set.py
resqpy/grid/face_functions.py
resqpy/grid/faults.py
resqpy/model/_xml.py
tests/unit_tests/grid/test_faults.py

defensive coding fix for set_face_set_gcs_list_from_dict function

---

resqpy/olio/load_data.py
resqpy/olio/vdb.py
tests/unit_tests/olio/test_vdb.py

Could someone please check my tests as I've not worked with byte arrays before

Vdb numpy bug

---

resqpy/property/grid_property_collection.py
resqpy/rq_import/_import_vdb_ensemble.py
tests/unit_tests/rq_import/test_import_vdb_ensemble.py

Max, I think these changes can go into your test_import_vdb_ensemble branch – though I haven't tested them!

setting facet info when importing vdb properties

---

.readthedocs.yaml
docs/requirements-extras.txt

Closes #439
Screenshots of builds now working:
And the docs themselves:

Update docs config

---

resqpy/lines/_polyline.py
resqpy/olio/intersection.py
resqpy/olio/vector_utilities.py

...around finding point on line closest to a given point in the xy plane

Polyline enhancements

---

resqpy/model/_forestry.py
resqpy/model/_model.py
resqpy/model/_xml.py
resqpy/olio/triangulation.py
resqpy/surface/_surface.py

This functionality will improve the triangulation of fault planes

adding reorient option for triangulation of a point set

---

resqpy/surface/_base_surface.py
resqpy/surface/_combined_surface.py
resqpy/surface/_pointset.py
resqpy/surface/_triangulated_patch.py

This change adds some trimming methods to the PointSet class

PointSet trimming methods

---

resqpy/property/_collection_get_attributes.py
resqpy/property/_collection_support.py
resqpy/property/property_collection.py
tests/unit_tests/well/test_wellbore_marker_frame.py

This change allows wellbore marker frames to be the supporting representation for properties, with indexable elements of nodes or intervals.

wellbore marker frame support for properties

---

resqpy/fault/_grid_connection_set.py
resqpy/grid_surface.py
resqpy/olio/wellspec_keywords.py

also some small changes to handling of edge effects in find faces to represent surface regular.

caching of gcs arrays optionally done at initialisation

---

resqpy/well/_wellbore_marker.py

– GeologicBoundaryKind type in marker

bug fix for wellbore marker frame create xml

---

resqpy/rq_import/_import_nexus.py

...  on vdb import for single case, all grids

setting facet info for recurrent Nexus properties

---

.github/actions/prepare-poetry/action.yml

Should fix issue with bad cached python interpreter.
Opened a related issue in the "install-poetry" action: https://github.com/snok/install-poetry/issues/82

Increment cache of python installation

---

resqpy/grid_surface.py
resqpy/property/property_collection.py

singleton() and single_array_ref() methods enhanced

adding multiple_handling optional arg to PropertyCollection methods

---

pyproject.toml

Miniature PR to help debug current issue with GitHub Actions. Will not merge until CI pipeline works..
Update: ready to merge. I still see an issue with CodeCov not working, but everything else seems ok.

Remove beta tag

---

.github/actions/prepare-poetry/action.yml

Implementing CI improvements from discussion in thread: https://github.com/snok/install-poetry/issues/82

More robust poetry installation

---

resqpy/fault/_grid_connection_set.py
resqpy/lines/_polyline.py
resqpy/surface/_surface.py
resqpy/surface/_triangulated_patch.py

also  gcs logging message improvements

option for quad triangles in horizontal surface

---

resqpy/grid_surface.py
resqpy/property/_collection_get_attributes.py
resqpy/property/_collection_support.py
resqpy/property/property_collection.py
resqpy/property/property_common.py
resqpy/surface/_surface.py
tests/unit_tests/property/test_property.py
tests/unit_tests/test_grid_surface.py

and optimised find faces to represent surface optionally returning triangle indices property

Support for TriangulatedSet properties

---

resqpy/lines/_polyline.py
resqpy/olio/vector_utilities.py
tests/unit_tests/lines/test_lines.py

also, point distance to line handling zero length line segment

polyline area now handling concave polylines

---

resqpy/fault/_grid_connection_set.py
resqpy/grid/_regular_grid.py
resqpy/model/_model.py
resqpy/model/_xml.py
resqpy/multiprocessing/multiprocessing.py
resqpy/multiprocessing/wrappers/grid_surface.py
tests/unit_tests/multiprocessing/test_wrapper_grid_surface.py

Enhancements to the multiprocessing package and related modules, especially for the intersection of surfaces with regular grids.

multiprocessing enhancements

---

resqpy/grid_surface.py
resqpy/multiprocessing/wrappers/grid_surface.py
tests/unit_tests/test_grid_surface.py

…(optimised) find cell faces regular ...

adds depths as optional return property from multiprocessing

---

resqpy/property/property.py
resqpy/surface/_mesh.py

This change introduces a Mesh class method to create a reg&z flavour mesh from a columns property for an aligned regular grid.

mesh class method from aligned regular grid columns property

---

resqpy/crs.py
tests/unit_tests/test_crs.py

potential fix for Crs.is_right_handed_xyz() reported bug

---

resqpy/rq_import/_add_surfaces.py

The function, used when importing surfaces, had complicated options around hdf5 file name and ext uuid handling. This change simplifies the code to strip out those options and make use of the resqpy default behaviour.

stripping out explicit handling of hdf5 access from add surfaces

---

resqpy/crs.py
resqpy/derived_model/_add_single_cell_grid.py
resqpy/multiprocessing/multiprocessing.py
resqpy/time_series/_functions.py

- crs equivalence now requiring same extra metadata
- add_single_cell_grid now with uom arguments
- multiprocessing recombination with time limits on wait

crs .EQ. testing extra metadata etc.

---

resqpy/grid_surface.py
resqpy/multiprocessing/__init__.py
resqpy/multiprocessing/wrappers/grid_surface.py
resqpy/multiprocessing/wrappers/grid_surface_mp.py
resqpy/olio/triangulation.py
resqpy/olio/vector_utilities.py
resqpy/property/_collection_add_part.py
resqpy/property/property_collection.py
resqpy/property/property_common.py
tests/unit_tests/conftest.py
tests/unit_tests/multiprocessing/test_wrapper_grid_surface.py
tests/unit_tests/olio/test_triangulation.py

This change adds the option to generate a grid cells boolean property indicating which side of a surface each cell is on, as a side effect of finding faces to represent the surface.

Regular grid enhancements

---

resqpy/grid_surface.py
resqpy/olio/vector_utilities.py
resqpy/surface/_surface.py
tests/unit_tests/olio/test_vector_utilities.py

This change adds a triangle specific version of the njit'ed points in polygon to squeeze a little more speed from the find faces for surface regular optimised functionality.

triangle specific version of points in polygon

---

resqpy/grid_surface.py
resqpy/olio/vector_utilities.py
tests/unit_tests/test_grid_surface.py

This change introduces an optimised version of points in triangles that is designed for aligned regular grids.

points in triangles version optimised for aligned grids

---

resqpy/multiprocessing/__init__.py
resqpy/multiprocessing/multiprocessing.py
resqpy/multiprocessing/wrappers/mesh_mp.py

> making all uuid types Union[UUID, str]
> adding success required argument to new mesh batch function

tidy up of multiprocessing wrt. new mesh wrapper

---

resqpy/grid_surface.py
resqpy/olio/vector_utilities.py
resqpy/well/_blocked_well.py

and other small changes, including adding a vector utilities function to create a rotation matrix based on a vector (target direction for positive z axis)

well blocking avoiding grid copy for aligned regular grids

---

resqpy/grid_surface.py

removing njit from grid_surface.bisector_from_faces() 

---

resqpy/olio/vector_utilities.py
resqpy/well/_blocked_well.py
tests/unit_tests/olio/test_vector_utilities.py

This change corrects the rotation_matrix_3d_vector() function so that a positive z axis vector will be rotated to the defining vector when multiplied by the rotation matrix.
The BlockedWell class is also enhanced with a few new, small, methods.

correction of vector utilities rotation_matrix_3d_vector()

---

resqpy/model/_xml.py
resqpy/multiprocessing/multiprocessing.py
resqpy/olio/vector_utilities.py
resqpy/property/_collection_create_xml.py

Property min & max metadata values constrained to integers for discrete data types.

Property min & max metadata values 

---

resqpy/lines/_polyline.py

handling 2 or 3 dimensional optional start and end points when creating a polyline from a trimmed polyline.

minor bug fix for polyline from trimmed polyline method

---

resqpy/well/_blocked_well.py

New method on blockedwell to allow a list of uuids for grid properties to be provided, and added as properties on the blockedwell. Only indexableelement of 'cells' accepted.

Add method to blocked well to pull grid properties

---

resqpy/grid/_regular_grid.py
resqpy/grid_surface.py
resqpy/lines/_polyline.py
resqpy/multiprocessing/wrappers/blocked_well_mp.py
resqpy/multiprocessing/wrappers/grid_surface_mp.py
resqpy/property/_collection_add_part.py
resqpy/property/_collection_create_xml.py
resqpy/property/property_collection.py
resqpy/property/property_common.py

property collection * and none options on selections, const value selectable, other minor changes

property collection * and none options on selections

---

resqpy/model/_forestry.py
resqpy/model/_model.py
resqpy/multiprocessing/multiprocessing.py
resqpy/multiprocessing/wrappers/blocked_well_mp.py
resqpy/multiprocessing/wrappers/grid_surface_mp.py
resqpy/multiprocessing/wrappers/mesh_mp.py
resqpy/olio/vdb.py
resqpy/property/_collection_add_part.py
resqpy/property/_collection_create_xml.py
resqpy/rq_import/_import_nexus.py
tests/unit_tests/property/test_property.py

- Preferring "rock permeability" in new xml
- Only applying string lookup table to discrete (not continuous) properties
- Quiet argument when loading or saving a model
- Allowing hyphens in recurrent keywords in Nexus vdb handling
Nexus is a trademark of Halliburton

Property xml improvements

---

resqpy/rq_import/_add_surfaces.py

Fix of bug detected by Chloe Jones.

fix of crs_uuid omission bug in rq_import._add_surfces._add_single_surface()

---

resqpy/model/_xml.py

Fix of bug detected by Emma Nesbit and Chloe Jones.

crs references distinguishing time and depth

---

resqpy/surface/_pointset.py

applicable to Charisma and Irap imports

using np.loadtxt() in PointSet imports

---

resqpy/grid/_create_grid_xml.py
resqpy/grid/_grid.py

Updates to allow represented interpretations to be set on grid objects

Grid represented interpretation

---

resqpy/grid/_grid.py

Support_uuid rather than support argument to PropertyCollection

Bug in grid.py

---

resqpy/grid_surface.py
resqpy/multiprocessing/wrappers/grid_surface_mp.py
resqpy/organize/geobody_boundary_interpretation.py
resqpy/well/_blocked_well.py
tests/unit_tests/multiprocessing/test_grid_surface_mp.py
tests/unit_tests/test_grid_surface.py

This change enhances the find_faces... regular optimised function to support another optional return property: grid shadow.

grid surface supporting shadow return property

---

resqpy/surface/__init__.py
resqpy/surface/_surface.py
resqpy/surface/_tri_mesh.py
tests/unit_tests/surface/test_tri_mesh.py

The TriMesh class is a resqpy class derived from Mesh (which itself represents RESQML Grid2dReperesentation objects).  The TriMesh class covers a roughly rectangular area with tessellated equilateral triangles.

initial code for TriMesh class

---

resqpy/weights_and_measures/nexus_units.py
resqpy/well/_blocked_well.py
tests/unit_tests/test_weights_measures.py

This represents  a small breaking change to the name of the optional argument to nexus_units()

small change to nexus units argument, to handle over pv option

---

resqpy/lines/_polyline.py

Update lines to handle geobodyboundaryinterpretations

Update lines to handle geobodyboundaryinterpretations

---

resqpy/derived_model/_gather_ensemble.py
resqpy/model/_catalogue.py
resqpy/model/_forestry.py
resqpy/model/_model.py
resqpy/model/_xml.py
resqpy/multiprocessing/multiprocessing.py
resqpy/multiprocessing/wrappers/blocked_well_mp.py
resqpy/multiprocessing/wrappers/mesh_mp.py
resqpy/olio/consolidation.py
resqpy/olio/uuid.py
tests/unit_tests/derived_model/test_derived_model.py
tests/unit_tests/model/test_model.py
tests/unit_tests/multiprocessing/test_grid_surface_mp.py

This performance change introduces a new dictionary attribute to the Model class: uuid_rels_dict, and makes use of it when filtering parts list by related uuid.  This reduces the amount of xml searching needed for such filtering, and reduces the number of times hexadecimal strings representing a uuid need to be converted to an int.

Model related uuids refactor

---

resqpy/model/_model.py
resqpy/model/_xml.py
resqpy/multiprocessing/__init__.py
resqpy/multiprocessing/multiprocessing.py
resqpy/well/_blocked_well.py
resqpy/well/well_object_funcs.py

This change improves the setting of the Title field in xml object references. It also attempts to improve the setting of titles for some well classes.

Ref node title

---

resqpy/olio/intersection.py
resqpy/olio/uuid.py
resqpy/olio/vector_utilities.py
resqpy/surface/_tri_mesh.py
tests/unit_tests/olio/test_uuid.py
tests/unit_tests/olio/test_vector_utilities.py

This change enhances the TriMesh class with a method for interpolating z values at zero crossing points on triangle edges.

New methods in TriMesh

---

resqpy/olio/xml_et.py

small optimisation to xml tag finding functionality

endswith name matching in xml functions

---

resqpy/surface/_surface.py
tests/unit_tests/surface/test_surface.py

This change adds a method to the Surface class, for sampling (interpolating) z at a given xy location

new Surface method for sampling z at xy location

---

resqpy/olio/xml_et.py
tests/unit_tests/olio/test_xml_et.py

This change is intended to speed up the list_obj_references() function a bit.

small optimisation of xml list_obj_references()

---

resqpy/organize/boundary_feature.py
resqpy/organize/boundary_feature_interpretation.py
resqpy/organize/earth_model_interpretation.py
resqpy/organize/fault_interpretation.py
resqpy/organize/fluid_boundary_feature.py
resqpy/organize/frontier_feature.py
resqpy/organize/generic_interpretation.py
resqpy/organize/genetic_boundary_feature.py
resqpy/organize/geobody_boundary_interpretation.py
resqpy/organize/geobody_feature.py
resqpy/organize/geobody_interpretation.py
resqpy/organize/geologic_unit_feature.py
resqpy/organize/horizon_interpretation.py
resqpy/organize/rock_fluid_unit_feature.py
resqpy/organize/tectonic_boundary_feature.py
resqpy/organize/wellbore_feature.py
resqpy/organize/wellbore_interpretation.py

This change adds an originator argument to the initialisation methods of each of the organize classes.

adding originator argument to init methods of organize classes

---

resqpy/surface/_tri_mesh.py
tests/unit_tests/surface/test_tri_mesh.py

This change adds a handful of xy array methods to the TriMesh class, equivalent to existing single point methods

adding array methods to TriMesh

---

resqpy/olio/triangulation.py
resqpy/surface/_surface.py
tests/unit_tests/olio/test_triangulation.py
tests/unit_tests/surface/test_surface.py

This change adds:
- an axial edge crossings method to the Surface class
- functions for identifying rim loops for triangulated sets

axial edge crossing method for Surface; rim edge functions

---

resqpy/property/property_common.py
resqpy/property/well_log_collection.py
resqpy/well/_wellbore_frame.py
tests/unit_tests/conftest.py

This change is in preparation for using wellbore frame properties with indexable elements of intervals. Here the well logs are identified as having indexable elements of nodes.

separating well logs from other frame properties

---

README.md
resqpy/olio/wellspec_keywords.py
resqpy/time_series/__init__.py
resqpy/time_series/_time_series.py
tests/unit_tests/time_series/test_time_series_functions.py

also minor change to contact email address

adding colloquial_date() function to time series module

---

resqpy/lines/_common.py
resqpy/lines/_polyline_set.py
tests/unit_tests/lines/test_polyline_set.py

This change resolves issue #458

fixes issue with polyline set when mixed closed indications

---

resqpy/olio/vector_utilities.py
tests/unit_tests/olio/test_vector_utilities.py

... and bug fix for points_direction_vector()

a few more unit tests for olio.vector_utilities functions

---

resqpy/olio/triangulation.py
tests/unit_tests/olio/test_triangulation.py

The olio.triangulation.surrounding_xy_ring() function adds a ring of points at some distance from a point set, and is used to extend surfaces beyond their mapped area.  This change adds the option, enabled by default, for a second ring of points, close to the originals.  This is to reduce unwanted triangulation artefacts when the original point set has a concave hull.

inner ring option when creating a surrounding ring for a point set

---

resqpy/olio/triangulation.py
tests/unit_tests/test_grid_surface.py

...to be compatible with previous version
this change leaves the new functionality in place but sets the default behaviour to be compatible with what was there before

reverting default surround_xy_ring() behaviour 

---

resqpy/model/_xml.py
resqpy/olio/xml_et.py
tests/unit_tests/model/test_model.py

improved setting of missing title to untitled

---

resqpy/grid_surface/__init__.py
resqpy/grid_surface/_find_faces.py
resqpy/grid_surface/grid_surface_cuda.py
resqpy/olio/intersection.py
resqpy/olio/triangulation.py
resqpy/olio/vector_utilities.py
tests/unit_tests/olio/test_vector_utilities.py
tests/unit_tests/test_grid_surface.py

`pytest-cov` doesn't yet support the test coverage of functions using the `njit` decorator. These functions have been manually checked and ignored from the coverage reports

Update Coverage of JIT functions

---

resqpy/property/_property.py
resqpy/property/property_common.py
tests/unit_tests/property/test_property.py
tests/unit_tests/rq_import/test_import_vdb_ensemble.py

Also limits 'region initialization' expected property kind to certain Nexus keywords.
Nexus is a trademark of Halliburton.

Adding realization() method to Property class

---

resqpy/olio/write_hdf5.py
resqpy/property/_property.py
resqpy/property/property_collection.py
tests/unit_tests/olio/test_write_hdf5.py

This change introduces options for using hdf5 chunks and compression.

hdf5 chunks and compression options

---

resqpy/grid/_regular_grid.py
resqpy/model/_forestry.py
resqpy/multi_processing/_multiprocessing.py
resqpy/olio/consolidation.py
tests/unit_tests/model/test_model.py

When blocked wells are created only some of the expected relationships with other objects are added. This change is to correct that bug.

WIP: fix missing blocked well relationships

---

resqpy/model/_catalogue.py
resqpy/multi_processing/wrappers/blocked_well_mp.py
resqpy/well/well_object_funcs.py

Do not merge – branch for debugging only

improvements to well_name function

---

resqpy/well/_trajectory.py
tests/unit_tests/well/test_trajectory.py

This change adds an inclinations() method to the Trajectory class, which returns a numpy array of inclinations of intervals, in degrees.

adding inclinations() method to Trajectory class

---

resqpy/well/_blocked_well.py
tests/unit_tests/well/test_blocked_well.py

Enhancement to the blocked well add_grid_property_to_blocked_well method to ensure the string lookups are added when categorical parts are added from a grid.

Update add_grid to handle string lookup uuids

---

resqpy/property/well_interval_property_collection.py

Update to ignore cells/intervals outside of the grid - which are represented with -1 (null) values in the cell_grid_link array.

Update well_interval_property_collection.py to handle BlockedWell properties with null cells

---

resqpy/surface/_pointset.py

This patch fixes a bug affecting the shape of point set data when creating from a multi-dimensional array of source points.

bug fix when creating point set from multi dimensional array

---

resqpy/property/_collection_get_attributes.py
tests/unit_tests/property/test_property.py

Adds more checks for all NaN arrays before attempting nanmin or nanmax, in property processing.

more defence against all nan arrays in property processing

---

.github/workflows/ci-publish.yml

Implement Trusted Publishing for uploading package to PyPI

---

resqpy/olio/wellspec_keywords.py

Adding `INCLUDE` as a keyword (in addition to the existing `WELLSPEC`, `WELLMOD`, `TIME`) to trigger the incrementing to a new well during the extraction of wells within a wellspec file in `resqpy.olio.wellspec_keywords.get_well_data`

Wsk skip comments

---

resqpy/fault/_grid_connection_set.py
resqpy/olio/relperm.py
resqpy/property/_collection_add_part.py
resqpy/property/property_collection.py
tests/unit_tests/fault/test_fault.py

Improvements to the GridConnectionSet append() method and new class method for merging grid connection sets and their properties.

gcs merging functionality

---

resqpy/property/property_collection.py
tests/unit_tests/conftest.py
tests/unit_tests/property/test_property.py

Adding unit test for PropertyCollection.add_similar_to_imported_list()

Add similar test

---

resqpy/property/property_common.py
tests/unit_tests/property/test_property.py

Fixes a buglet affecting the property_parts() functions when facet info is provided without a property kind.

Property parts bug fix

---

resqpy/surface/_surface.py
tests/unit_tests/surface/test_surface.py

This change adds a class method to the Surface class which creates a down-sampled version of an existing surface. It selects a subset of points at random from the source surface and then re-triangulates.

Surface downsampling class method added

---

resqpy/lines/_polyline.py
resqpy/lines/_polyline_set.py
tests/unit_tests/lines/test_lines.py
tests/unit_tests/lines/test_polyline_set.py

Improved handling of closed polylines when importing from IRAP format.

Polyline closure

---

resqpy/grid/_defined_geometry.py
resqpy/grid/_grid_types.py
resqpy/grid_surface/_blocked_well_populate.py
resqpy/well/_blocked_well.py
tests/unit_tests/grid/test_defined_geometry.py
tests/unit_tests/well/test_blocked_well.py

Make filling of missing grid points more rugged.

Grid points fill bug

---

resqpy/surface/_tri_mesh.py

This patch improves the handling of NaN coordinates in the TriMesh class.

better handling of NaN coordinates in TriMesh

---

resqpy/surface/_surface.py
tests/unit_tests/surface/test_surface.py

This patch adds an optional argument, _exclude_nans_ (default False), to the Surface.from_tri_mesh() class method. When True, any NaN points in the tri mesh will be filtered out, along with any triangles using those points.

adding optional filtering out of NaN points in Surface.from_tri_mesh()

---

resqpy/surface/_tri_mesh.py
tests/unit_tests/surface/test_tri_mesh.py

Adds a TriMesh.is_compatible_with() method which returns True if another tri mesh has the same xy layout as this one.

Tri mesh compatibility

---

resqpy/property/__init__.py
resqpy/property/attribute_property_set.py
tests/unit_tests/property/test_attribute_property_set.py

Add an AttributePropertySet class derived from PropertyCollection to allow for attribute syntax read access to properties and their metadata.

Attribute pc

---

resqpy/property/__init__.py
resqpy/property/attribute_property_set.py

Adds a public function for generating a key suitable for an AttributePropertySet property.

adding make_aps_key() function

---

resqpy/rq_import/_import_nexus.py
resqpy/rq_import/_import_vdb_all_grids.py
tests/unit_tests/rq_import/test_import_vdb_ensemble.py

Allow list of required grid properties when importing from Nexus vdb.
Nexus is a trademark of Halliburton.

optional selection of named vdb grid properties during import

---

resqpy/model/_catalogue.py
resqpy/model/_model.py
resqpy/model/_xml.py
resqpy/olio/xml_et.py
resqpy/property/attribute_property_set.py
resqpy/property/property_collection.py
tests/unit_tests/conftest.py
tests/unit_tests/model/test_model.py
tests/unit_tests/olio/test_xml_et.py
tests/unit_tests/property/test_attribute_property_set.py

Improving access to the 'source' extra metadata item. Resolves issue #812

Source access

---

resqpy/model/_forestry.py
resqpy/well/_trajectory.py
tests/unit_tests/multiprocessing/test_function_multiprocessing.py

This change fixes an issue regarding missing xml relationships after consolidation.

Time series properties rels

---

resqpy/model/_xml.py
resqpy/property/_collection_add_part.py
resqpy/property/property_collection.py
tests/unit_tests/derived_model/test_derived_model.py

This change fixes the issue with constant boolean properties. Resolves issue #810

const bool property fix

---

resqpy/well/_blocked_well.py

Bw df unit conversion doc string

---

resqpy/fault/_grid_connection_set.py
tests/unit_tests/fault/test_fault_connection_set.py

gcs grid faces method cleaned up for feature index

WIP: miscellaneous optimisations

---

resqpy/grid_surface/_find_faces.py

Correcting a type in find faces module.

type correction

---

resqpy/grid_surface/_find_faces.py

Fixes issue with find faces: If one or more axes had no faces, find faces failed in getting the bounding box from the indices.

handling None faces when getting bounding box from indices in find faces

---

resqpy/grid_surface/_find_faces.py

Another patch to defend against all faces None

setting open arrays to True when faces are None

---

resqpy/grid_surface/_find_faces.py

Repairing an embarrassing bug in the function finding the bounding box from face indices.

cut and paste bug fix in bounding box from indices

---

resqpy/grid_surface/_find_faces.py

Fixes a bug occasionally affecting packed bisector generation due to counting of padding bits.

clearing packed bisector padding bits after filling outside box

---

resqpy/grid_surface/_find_faces.py

Resolving numba typing issues with two functions involved in packed bisector generation.

jitting two more functions

---

resqpy/grid/_grid_types.py
resqpy/grid/_regular_grid.py
resqpy/unstructured/_hexa_grid.py
resqpy/unstructured/_prism_grid.py
resqpy/unstructured/_pyramid_grid.py
resqpy/unstructured/_tetra_grid.py
resqpy/unstructured/_unstructured_grid.py
tests/unit_tests/unstructured/test_unstructured.py

Enhances the other grid classes, as well as the any_grid function, with a load_inactive argument like in the Grid class.

adding load_inactive argument to all grid class initialisers

---

resqpy/surface/_surface.py
tests/unit_tests/surface/test_surface.py

New method to refine triangles on the edges/tears within triangulated sets (resqpy.surface.Surfaces).

New surface method: Resample surface edges/tears

---

.github/workflows/ci-tests.yml
pyproject.toml

This change adds support for python 3.12

Update pyproject.toml to support python 3.12

---

resqpy/grid_surface/_find_faces.py

This patch is an optimisation of the find faces... bisector generation, adding an njit function for update of composite bisectors when using packed bisector arrays in combination with patchwork.

njit function for update of composite bisector

---

resqpy/grid_surface/_find_faces.py

Further optimisation of the njit update function for the composite packed bisector in find faces...

Patch box for packed composite bisector update

---

resqpy/olio/triangulation.py

To avoid circular import warnings

Update triangulation.py with future import
