bp/resqpy

- tests/test_volume.py
Fixes an intermittent failure in the unit tests.
Currently one test has a random element without a fixed seed, and fails approximately half of the time.
> Permissive comparisons in further volume tests

- README.md
Finishes the roll-out of the automatically generated documentation, by providing hyperlinks and status badges on the README.
Documentation is stored in the `docs/` directory; more content can be added here over time.
Closes #3
> Add badges and links to docs to README

- .gitignore
- .readthedocs.yaml
- docs/conf.py
- pyproject.toml
- resqpy/__init__.py
- setup.cfg
This updates the build config to **version** the build according to the latest git tag.
Git tags are used as the single source of truth of the version. The version will then appear in several places:
- The built python package (i.e. when `python -m build` is run, the wheel file has the version in the name)
- The `resqpy.__version__` attribute
- The top right and bottom left of https://resqpy.readthedocs.io/
Closes #2 
References:
- https://packaging.python.org/guides/single-sourcing-package-version/
- https://github.com/pypa/setuptools_scm/
> Add version to packaging config

- .github/workflows/ci-publish.yml
- .github/workflows/ci-tests.yml
- .gitignore
- README.md
Adds a CI workflow for making new releases, and adds instructions to the README on how to trigger a release.
There are three sequential jobs, that will be triggered by a git tag:
- Build a python distribution (`python -m build`)
- Run pytest against the installed distribution (_not_ against the source repo)
- Publish to PyPI
Closes #9 
Links:
- CI with Github Actions: https://docs.github.com/en/actions
- PEP517-compliant builds: https://www.python.org/dev/peps/pep-0517/
- Publishing distributions: https://packaging.python.org/tutorials/packaging-projects/
> Add CI pipeline to make release

- .github/workflows/ci-tests.yml
This change removes the posting of messages for individual unit tests during CI processing.  "All tests" result is still obvious.
> commenting out posting of unit test results message in CI script

- .github/workflows/ci-tests.yml
- README.md
- setup.cfg
Tested which python versions are supported: tests pass with 3.6+, but fail for 2.7 and 3.5. 
So, adding the list of supported versions to:
- CI tests (matrix strategy)
- PyPI classifier listing
- Badge on README front page
Also added a `Development Status :: 4 - Beta` classifier to `setup.cgf`, which is listed on the PyPI pacakge and will appear as a README badge. 
Other options for this classifier could be:
```
Development Status :: 1 - Planning
Development Status :: 2 - Pre-Alpha
Development Status :: 3 - Alpha
Development Status :: 4 - Beta
Development Status :: 5 - Production/Stable
Development Status :: 6 - Mature
Development Status :: 7 - Inactive
```
> Explicit python version support, set development status

- docs/_templates/custom-class-template.rst
- docs/conf.py
- docs/requirements.txt
- resqpy/model.py
- resqpy/well.py
Closes #16 
Uses the autoclasstoc library to enhance our Sphinx documentation with customised sections when listing out methods of a class: https://autoclasstoc.readthedocs.io/en/latest/index.html
Enables us to separate out high- and low-level methods in the docs, to make it a bit more tractable when the table gets very long. The enables us to promote a method to a special "High-level methods" section by including `:meta high-level:` at the end of the docstring.
The new-style documentation can be previewed here:
https://resqpy.readthedocs.io/en/split-docs/
> Use autoclasstoc to separate out "high level" and "low level" methods

- .github/workflows/ci-tests.yml
- setup.cfg
As we want to use `datetime.fromisoformat`, which is in 3.7+ only
> Drop support for python 3.6

- resqpy/derived_model.py
- resqpy/model.py
BOOTs Maps workflow is taking too long to consolidate large ensembles (time grows worse than linear with number of realisations). This change aims to provide some speedup when the calling code has some 'knowledge' about the ensemble.
> Optimising consolidation

- README.md
An easier way to see our coverage, avoids having to remember the URL of the CodeCov website:
> Add CodeCov badge to README

- resqpy/derived_model.py
This change is needed to allow later processing steps to work with the grid connection set(s) after scaling of fault throws.
> grid connection set inheritance in derived model fault throw scaling functions

- .github/codecov.yml
- .github/workflows/ci-tests.yml
- .readthedocs.yaml
- docs/CONTRIBUTING.rst
- docs/conf.py
- docs/requirements.txt
- setup.cfg
The docs do not currently show the version number correctly when hyperlinks are copied and pasted around. I think this is because the `resqpy` package is not properly pip-installed when the docs are build - this should fix that issue.
Also suggest including the documentation dependencies explicitly in the package requirements (i.e. in `setup.cfg`), so that a developer can install everything needed with:
```
pip install .[tests,docs]
```
> Fix docs version numbers, explicit docs dependencies

- resqpy/olio/base.py
- resqpy/olio/xml_et.py
- resqpy/organize.py
- resqpy/well.py
- tests/test_base.py
A second, simpler attempt to implement a simple Base Class for resqml objects, that handles the generic stuff like:
- Standardising on using `uuid` as the primary key
- Setting citation title and orginator attributes
- Pretty display methods, including HTML ipython
Closes #20
Closes #19
Similar to #44 , but with fewer changes for a first step.
In future, could be extended to implement loading and saving simple (not nested) properties to XML and HDF5
> Implement simple base class

- resqpy/time_series.py
- tests/test_timeseries.py
New timeseries functions to merge together several timeseries into one sorted timeseries and return the resulting timeseries object. Also created a convenience routine to return datetime objects which may entail slicing off the "+Z" timezone character from the timestamps. 
This works only based off of timeseries uuids.
I created tests in tests/test_timeseries.py, but I'm not sure how to configure the CI workflow to run them automatically
> Merging timeseries

- resqpy/property.py
This change is needed for Jeremy Tillay's workflow, where a property array is pre-filled and then the hdf5 array is updated in slices. The change allows the metadata min and max values to be updated once the array is fully populated.
> patch_min_max_for_part() method added to PropertyCollection

- resqpy/olio/base.py
- tests/test_base.py
Switching to use `rqet.part_name_for_object` as suggested by Andy. Makes progress towards #17
> Faster implementation of self.part

- resqpy/model.py
- resqpy/olio/uuid.py
- tests/test_model.py
This change adds code to the Model class to maintain a second dictionary kept in sync with parts_forest. The new dictionary maps from uuid (as int) to part name and should hopefully speed up the lookup of objects when starting from a uuid.
> WIP: UUID keys in model

- resqpy/time_series.py
- tests/test_timeseries.py
There was a bug in previous PR https://github.com/bp/resqpy/pull/32
Fixed to strip uppercase z from timestamp strings instead of lowercase. 
Also added more tests to check that merging timeseries does not return duplicate timestamps.
> Fixing timeseries merging

- resqpy/property.py
Previously rq_import was marking pore volume data from 'ENGLISH' vdb as having uom of ft3. This change corrects this to bbl, which is what Nexus seems to output.
Resolves issue #84
> guess uom returning bbl for pore volume when grid crs in ft

- resqpy/model.py
- resqpy/property.py
- resqpy/well.py
- tests/conftest.py
- tests/test_well.py
Adds a method `WellLogCollection.add_log`, to enable well logs to be created from scratch and saved to disk.
Supporting changes:
- Unit tests, including for previous functionality for export of logs as pandas or lasio.LasFile
- rename of `log.name` to `log.title`
- rename of `WellLogCollection.logs()` to `WellLogCollection.iter_logs()`
- Update of a few other tests, to stop using deprecated keywords (and thus reduce number of pytest warnings).
> Well log creation and conversion

- .github/workflows/codeql-analysis.yml
For now, suggest not running CodeQL scanning on every commit on Pull Requests. The analysis is still run on master, and can be checked before releases are run.
> Edit analysis frequency to speed up CI

- resqpy/grid.py
- resqpy/grid_surface.py
- resqpy/lines.py
- resqpy/model.py
- resqpy/rq_import.py
- resqpy/surface.py
- resqpy/well.py
- tests/test_surface.py
Bringing resqpy surface classes in line with BaseResqpy and uuid way of working.  This will be a breaking change, removing the extraneous extract_from_xml arguments and also unused parent node argument to create_xml() methods.
> Surface upheaval

- resqpy/olio/weights_and_measures.py
This small change adds aliases for siemens and millisiemens, required by a Bifröst Labs notebook test.
> adding alias for siemens (mho for S and mmho for mS)

- docs/tutorial/grid_properties.rst
- Adds required blank line after some python code block markup lines.
- Mentions the separate uom tutorial in the uom section
> minor changes to the grid properties tutorial

- resqpy/model.py
A very minor enhancement - allowing resqpy models to be created from pathlike objects, rather than just strings.
Closes #165
> Handle PEP 517 pathlike inputs

- resqpy/grid.py
- resqpy/model.py
- resqpy/rq_import.py
- setup.cfg
This change makes pytest fail if a respy-internal DeprecationWarning is raised within the test suite. This should help us ensure that we are not calling any soon-to-be-deprecated functions from within the other functions.
> Modify pytest to fail if internal Deprecation warnings are raised

- resqpy/grid.py
Previously, only a Discrete (not Categorical) property of local property kind 'active' would be recognised when setting the resqpy Grid inactive attribute.  This change recognises the active property if it is either Discrete or Categorical.
> active property may be discrete or categorical; resolves #185

- resqpy/property.py
The PropertyCollection.set_support() method clears the supporting representation for multi-support or no support property collections.  This change causes the model attribute of the PropertyCollection to remain unchanged in those circumstances (previously it was also cleared).
> Leaving model attribute set in PropertyCollection.set_support()

- resqpy/model.py
This change is to provide method(s) allowing the creation of a temporary (mock) supporting representation, when working with a dataset where the actual supporting representation is not included.
This relates to issue #197
> new method in Model for temp supporting representation

- resqpy/olio/triangulation.py
- resqpy/surface.py
The Delauney triangulation code uses a superimposed container triangle around the set of points.  With certain patterns of points, the resulting triangulation could have slight concavities.  That would not be an issue for some applications (for example triangulating a horizon or fault surface from points).  However, the use of the Delauney triangulation for representing unstructured grid cell faces requires there to be no such concavities.
> container triangle for Delauney triangulation expanded

- resqpy/time_series.py
- tests/test_timeseries.py
This change adds a new resqpy class, GeologicTimeSeries, which is designed to be used for RESQML TimeSeries objects which are on a geological timeframe.
Note that initial code changes were accidentally merged directly into master (sorry!)
Resolves issue #213
> WIP: support for geologic time series; closes issue #213

- resqpy/weights_and_measures.py
- tests/test_weights_measures.py
This change adds some more unit aliases, as used in some Nexus output.
Nexus is a trademark of the Halliburton Company.
> uom aliases added for some units used in Nexus output

- resqpy/model.py
This change updates the format string which is written into every citation block. Such a change should be applied each time there is a major or minor change in the latest tag.
> citation format string updated to resqpy 1.3

- resqpy/property.py
This change suppresses the property kind warning when the kind and expected kind are both one of 'length' or 'thickness'.
> suppressing property kind warning for length-thickness mismatches

- resqpy/grid.py
- tests/test_grid.py
fix for bug affecting reading of RegularGrid when no cell length properties present; resolves issue #222
> fix for bug affecting reading of RegularGrid; closes issue #222

- setup.cfg
Closes #227 
From experimentation:
- Pinning an older version of `sphinx-rtd-theme` seems to fix the issue
- Removing the `autoclasstoc` extension does _not_ fix the issue
- Changing the theme to "classic" does _not_ seem to fix the issue
> Pin sphinx_rtd_theme version

- resqpy/grid.py
- resqpy/olio/rq_print.py
- resqpy/property.py
- resqpy/time_series.py
- tests/test_property.py
This change provides a Grid method for overwriting the cached points (geometry) from an instance of a points property.  The property may have multiple realizations and/or time indices as usual.  This is primarily to support basin modelling or other geological processes affecting the geometry of strata.
> setting grid geometry from points property; resolves issue #223

- tests/test_unstructured.py
This is needed for grid to inherit crs.
> setting crs_uuid for surfaces in voronoi grid test

- resqpy/derived_model/__init__.py
- resqpy/olio/ab_toolbox.py
- resqpy/olio/box_utilities.py
- resqpy/olio/dataframe.py
- resqpy/olio/factors.py
- resqpy/olio/grid_functions.py
- resqpy/olio/keyword_files.py
- resqpy/olio/load_data.py
- resqpy/olio/relperm.py
- resqpy/olio/trademark.py
- resqpy/olio/transmission.py
- resqpy/olio/utility.py
- resqpy/olio/uuid.py
- resqpy/olio/vector_utilities.py
- resqpy/olio/wellspec_keywords.py
- resqpy/olio/write_data.py
- resqpy/olio/write_faults.py
- resqpy/olio/zmap_reader.py
- resqpy/surface/__init__.py
- setup.cfg
Supports progress towards #290 .
Changes `setup.cgf` to include a new flake8 plugin and error code.
> Add basic docstring checks to static analysis tests

- setup.cfg
I suggest always ignoring these two flake8 errors:
- `D202: No blank lines allowed after function docstring` : does not affect HTML docs.
- `D405: Section name should be properly capitalized` : docs will render fine either way.
Nb. These errors are not actually enabled at the moment in the CI suite; however, including the codes in the "ignore" list will ensure these checks aren't included when flake8 is run on the command line with `flake8 --select=D path/to/file.py`
See #290
> Ignore further unimportant pydocstyle error codes

- resqpy/derived_model/_dm_drape_to_surface.py
- resqpy/fault.py
- resqpy/grid.py
- resqpy/grid_surface.py
- resqpy/lines/_polyline.py
- resqpy/model.py
- resqpy/olio/box_utilities.py
- resqpy/olio/fine_coarse.py
- resqpy/olio/grid_functions.py
- resqpy/olio/intersection.py
- resqpy/olio/point_inclusion.py
- resqpy/olio/relperm.py
- resqpy/olio/xml_et.py
- resqpy/organize/__init__.py
- resqpy/organize/geobody_boundary_interpretation.py
- resqpy/property.py
- resqpy/rq_import.py
- resqpy/strata/_binary_contact_interpretation.py
- resqpy/surface/combined_surface.py
- resqpy/surface/pointset.py
- resqpy/surface/surface.py
- resqpy/surface/triangulated_patch.py
- resqpy/time_series.py
- resqpy/unstructured/_unstructured_grid.py
- resqpy/well.py
- setup.cfg
This change supports #290 by fixing docstring issues for the set of error codes starting with "D2".
Inevitably this required manually editing a large number of files, glad to say that's now done.
Three main changes:
-  `setup.py`: Includes the below error codes to the "include list"
-  `setup.py`: Adds D210, D402 and D417 to the "ignore list" (mostly false positives or unimportant)
- Many files: relevant fixes for existing broken docstrings.
Errors fixed:
```
D200: One-line docstring should fit on one line with quotes
D201: No blank lines allowed before function docstring
D205: 1 blank line required between summary line and description
D206: Docstring should be indented with spaces, not tabs
D207: Docstring is under-indented
D208: Docstring is over-indented
D209: Multi-line docstring …
```
> Fix D2xx error codes

- resqpy/olio/base.py
- resqpy/olio/box_utilities.py
- setup.cfg
Supports #290. Enables checks for below error codes, and includes fixes to existing broken docstrings.
```
D101: Missing docstring in public class
D105: Missing docstring in magic method
D106: Missing docstring in public nested class
D107: Missing docstring in init
D401: First line should be in imperative mood; try rephrasing
D403: First word of the first line should be properly capitalized
D410: Missing blank line after section
D411: Missing blank line before section
D412: No blank lines allowed between a section header and its content
D414: Section has no content
D415: First line should end with a period, question mark, or exclamation point
D416: Section name should end with a colon
D418: Function/ Method decorated with @overload shouldn’t contain a docstring
```
Once this is merged, …
> Fix D4xx error codes and most D1 codes

- resqpy/grid.py
- resqpy/property/property.py
- resqpy/property/property_collection.py
- resqpy/property/property_common.py
- resqpy/property/string_lookup.py
- resqpy/property/well_interval_property_collection.py
- resqpy/surface/surface.py
- resqpy/well.py
- setup.cfg
Closes #290
Updates our linter to include all "D" error codes, other than those in the "ignore" list. Expected to fail until all docstrings for public functions are written.
> Enable full set of docstring error codes

- resqpy/time_series/_from_nexus_summary.py
This bug fix affects importing from Nexus.  An error in the code meant that a TimeSeries object was not being created from the Nexus summary file information.  That in turn meant that no recurrent properties could be imported.
> fixes bug affecting TimeSeries from Nexus summary file

- resqpy/__init__.py
- resqpy/model/_model.py
- resqpy/model/_xml.py
- setup.cfg
Closes #342 
Adds a log message with the auto-generated `__version__` attribute. Also improves it slightly to ensure the version tag is picked up in a development setting even when the package was not properly pip-installed.
The package `setuptools_scm[toml]` is already a dependency under `setup_resquires`, but I propose adding it to the dev dependencies too.
This is what happens when the version is fetched for a development version (working from a local clone, rather than an installed release):
> Enable logging of true resqpy version

- .github/workflows/ci-tests.yml
- setup.cfg
- tests/test_resqpy.py
Adds a unit test to ensure version is being picked up correctly, and is PEP 440-compliant.
The `packaging` lib can be used to validate version strings. It's a small library already in our dependencies indirectly though `setuptools_scm`, but I've added it here explicitly to our dev dependencies.
> Add test for correct version string

- resqpy/__init__.py
- tests/test_resqpy.py
Previous implementation implicitly assumed that the calling code's current working directory was resqpy root, which is obviously not always the case.
> Ensure dev version number works when cwd is not repository root

- tests/test_olio_write_faults.py
Tests were writing to a permanent file before.
> Temp path added

- resqpy/grid/grid.py
- resqpy/grid/write_nexus_corp.py
- resqpy/property/grid_property_collection.py
When exporting grid properties to Nexus ascii files, the filenames need to include a realisation number if the property collection includes multiple realisations.
> appending realisation number to Nexus grid property file names

- .github/actions/prepare-poetry/action.yml
- .github/workflows/ci-tests.yml
Refactors the Poetry CI steps that install Python, Poetry and dependencies.
Separates jobs as a separate GitHub "action", that is re-used between the linting and unit test jobs to avoid duplication. Added further caching for speed.
The installation steps can be triggered from within a CI job with:
```yaml
- name: Install dependencies
uses: ./.github/actions/prepare-poetry
with:
python-version: 3.9
```
> Refactor poetry CI

- .github/workflows/ci-tests.yml
- pyproject.toml
Exploring whether resqpy can support Python 10. Confirmed on CI, it all looks good!
As per discussion on #432 , we might want to consider dropping support for python 3.7 . On
> Add support for python 10

- .github/workflows/ci-tests.yml
- pyproject.toml
Closes #432 
Adds a CI job that runs the unit tests against some older versions of our 3rd party libraries. 
Steps in the job:
1. Installs the usual dependencies, using the reusable "prepare poetry" action implemented in #431
2. Downgrades numpy to 1.19 and pandas to 1.1 (the lowest versions we claim to support in our `pyproject.toml` metadata
3. Runs pytest
I note that for some even older versions of pandas, the "downgrade" step takes ages (10+ minutes) then fails, as pip tries to build pandas from source rather than use a pre-built wheel. However, for the minimum versions we have now, the installation step works reasonably smoothly (~30 seconds).
> Test against older versions of dependencies

- resqpy/property/_collection_get_attributes.py
This issue was detected by Dominic Camilleri, who also proposed the fix included here.
> fix to property min max setting for discrete arrays when all elements masked out

- resqpy/olio/triangulation.py
- resqpy/surface/_surface.py
This option effectively allows a flange extension to be added when triangulating a point set
> Adding option to extend a point set with a surrounding ring before triangulation

- resqpy/well/_trajectory.py
This change checks that a referenced deviation survey is actually present before attempting to add it as an attribute of a resqpy Trajectory object, when initialising from xml.
> Check for presence of deviation survey when initialising trajectory

- resqpy/olio/triangulation.py
- resqpy/surface/_surface.py
when extending a point set with a flange ring of points, the previous radius factor argument is augmented with an optional absolute radius argument; the greater of the two radii values is used
> optional absolute radius argument for flange ring

- .github/dependabot.yml
We could try using Dependabot to flag updates to the lockfile. As I understand, this should raise PRs when new versions are available, and the CI will check these against the test suite.
In practice we might want a less frequent update (e.g. monthly), but I proposed it daily to check it works as expected.
> Add depandabot config

- resqpy/grid/_regular_grid.py
When loading an existing RegularGrid, resqpy looks for cell length properties to determine the implicit geometry. This change adds the clause of indexable being set to 'cells'.  (Note that the properties have constant values although they can optionally be written fully expanded.)
> specifying indexable of cells for RegularGrid cell size properties

- .github/actions/prepare-poetry/action.yml
- .github/workflows/ci-tests.yml
- poetry.lock
- pyproject.toml
- resqpy/grid_surface.py
[CVE-2021-34141](https://nvd.nist.gov/vuln/detail/cve-2021-34141) has been given for our currently pinned version of numpy (1.21.6), which is resolved in numpy 1.22. Update numpy requires us to drop support for python 3.7.
The CVE seems to be of questionable importance; the maintainers describe it as "[completely harmless](https://github.com/numpy/numpy/issues/18993)". 
But in any case, it is time for us to drop support for 3.7 according to the [NEP29 deprecation policy](https://numpy.org/neps/nep-0029-deprecation_policy.html):
- Support all minor versions of Python released in the prior 42 months
- Support all minor versions of NumPy/Pandas released in the prior 24 months
As this is a potentially breaking change, I suggest incrementing the semver major version on our next release.
> Drop python 3.7

- resqpy/surface/_surface.py
… for vertices and triangles
This should cater for files with, for example, 'CNXYZ' following numerical data on the vertices lines.
GOCAD is a trademark of Emerson
> GOCAD TSurf import lines truncated after numerical data

- resqpy/olio/fine_coarse.py
- tests/unit_tests/olio/test_fine_coarse.py
This change fixes a bug in the FineCoarse class proportions_for_axis() method when equal proportions is True for the axis and constant ratios is None for the axis.
> FineCoarse bug fix

- resqpy/fault/_grid_connection_set.py
- resqpy/grid/_points_functions.py
- tests/unit_tests/grid/test_points_functions.py
This change fixes a bug affecting Grid.coordinate_line_end_points() when K Gaps are present.
> fix of bug affecting Grid.coordinate_line_end_points()

- resqpy/grid_surface.py
This change applies the numba just in time decorator to the bisector_from_faces() function in the grid_surface.py module.
Currently fails at runtime.
> numba jit for bisector_from_faces()

- resqpy/grid_surface.py
- resqpy/olio/vector_utilities.py
- tests/unit_tests/test_grid_surface.py
This change removes use of the large centres array from the optimised find faces for surface functionality for aligned regular grids.  Support for the consistent side argument is also removed from that function.
> Remove centres intersect numba

- resqpy/olio/wellspec_keywords.py
- resqpy/well/_blocked_well.py
- resqpy/well/well_object_funcs.py
When creating a BlockedWell object from a wellspec file, the user must specify whether the usa_date_format is True (MM/DD/YYYY) or False (DD/MM/YYYY). Currently the usa_date_format variable defaults to False and there's no way to specify otherwise when creating a BlockedWell object. This PR adds the usa_date_format arg to the BlockedWell constructor as well as several supporting functions within resqpy/well/well_object_funcs.py.
> Blocked well dateformat

- resqpy/fault/_grid_connection_set.py
This update allows a trans_mult_uuid to be provided when using the 'write_simulator' method. If a uuid is provided, and this property exists on the gcs these values will be used as transmissibility multiplier values on the output file. If not provided, the default of 1.0 is used.
> Update gcs to write tmult values to nexus fault file

- resqpy/olio/read_nexus_fault.py
This pull request addresses two issues:
-In nexus deck, user doesn't need to specify what grid faults are associated with - default is ROOT. This pull request sets the default to 'ROOT' instead of None. 
-Current process of creating fault_df can potentially have mismatched series lengths, throwing an "All arrays must be of the same length" error.  Creating fault_df with a pd.concat() of all the individual fault df's is more robust and avoids this error.
> read_nexus_fault bug fixes

- resqpy/grid/_regular_grid.py
This sets the extra metadata as for a normal Ijk grid when creating xml for a RegularGrid and including geometry.
> cleans up extra metadata when storing a RegularGrid with a geometry

- resqpy/grid/_create_grid_xml.py
- resqpy/grid/_regular_grid.py
This change ensures that the PillarGeometryIsDefined xml is written for RegularGrids with lattice geometry.  Required for inter-operability with Fesapi and for RESQML schema compliance.
> always writing PillarGeometryIsDefined xml for grids

- resqpy/olio/vector_utilities.py
- resqpy/surface/_surface.py
- tests/unit_tests/surface/test_surface.py
A recent refactoring moved the computation of normal vectors into a Surface class method. During that change, the vectors reversed direction. This change is to return their direction to upwards pointing.
> Normal vectors to point upwards

- resqpy/multiprocessing/wrappers/grid_surface_mp.py
- resqpy/property/_collection_create_xml.py
- resqpy/property/property_collection.py
- resqpy/surface/_surface.py
- tests/unit_tests/model/test_model.py
- tests/unit_tests/multiprocessing/test_grid_surface_mp.py
- tests/unit_tests/property/test_property.py
- tests/unit_tests/rq_import/test_import_vdb_ensemble.py
This change causes automatic generation of a local property kind when adding a property with one of the 3 main abstract property kinds: 'continuous', 'discrete', 'categorical'. This change is needed for inter-operability with recent versions of Fesapi, and for strict adherence to one of the ancillary xml files in the RESQML v2.0.1 standard.
> WIP: auto generation of local property kinds when abstract kind specified

- resqpy/well/_blocked_well.py
This change resolves an issue whereby the null value for grid indices, as being stored in the xml metadata for blocked wellbore objects, was ending up as None. It will now default to -1.
> ensuring BlockedWell grid indices null value defaults to -1

- resqpy/olio/wellspec_keywords.py
Previous version had some misspecifications on how WELLSPEC block terminates.
-Removed kf.blank_line(file) as reason to break and return well data (user may have several blank lines withinin their wellspec block)
-Added "TIME" keyword as reason to break and return well data
-Added if len(words) == 0: break (end of file) to return well data
Have encountered this issue several times - where user has blank lines in middle of wellspec data, causing blocked well data to be added prematurely, or not at all (e.g. when blank line immediately follows IW JW L ... line)
> fix error in wellspec parsing

- resqpy/fault/_gcs_functions.py
In order to add nexus faults to a resqml model, resqpy.fault calls add_connection_set_and_tmults
This function concatenates all the fault include files into a single temp file 'faults_combined_temp.txt'
I have encountered several cases of RMS-exported fault include files not containing a trailing line break at the end of the file. This results in the last line of one file being merged with the first line of the next file in one line.
For example:
```
MULT	TX	ALL	MINUS	MULT
GRID	ROOT
FNAME	FAULT_EXAMPLE_A
1	10	26	26	16	100	1.0
1	10	27	27	16	100	1.0
1	10	28	28	16	100	1.0C  =====================================
C  
C  Exported from Grid_model_v1
C  
```
In the example above you can see the concatenation error on the last line of the FNAME definition "1.0C ====..."
Adding a .strip() + '\n' to …
> fault incl file concatenation fix

- resqpy/derived_model/_coarsened_grid.py
- resqpy/fault/__init__.py
- resqpy/fault/_gcs_functions.py
- resqpy/fault/_grid_connection_set.py
- resqpy/grid/_grid.py
- resqpy/grid/_xyz.py
- resqpy/grid_surface.py
- resqpy/multiprocessing/wrappers/grid_surface_mp.py
- resqpy/olio/fine_coarse.py
- resqpy/property/_collection_add_part.py
- resqpy/property/grid_property_collection.py
- resqpy/property/property_collection.py
- tests/unit_tests/fault/test_fault_connection_set.py
- tests/unit_tests/test_grid_surface.py
This change includes support for a time_series_uuid when adding a cached array to a PropertyCollection import list. (Previously the time series could only be identified at the later step of creating xml for the import list properties.)
> improvements to grid coarsening etc

- resqpy/fault/_gcs_functions.py
- resqpy/fault/_grid_connection_set.py
- resqpy/grid/_grid.py
This change adds options to set some transmissibility multipliers to zero, when combining properties from grid connection sets, based on boolean 'baffle' properties.
> Additional baffles when combining transmissibility multipliers

- docs/requirements-extras.txt
Fixes failing Sphinx builds, by pinning Sphinx version, avoiding breaking changes in `6.0.0`.
Link to build: https://readthedocs.org/projects/resqpy/builds/19316764/
Link to preview docs for this branch: https://resqpy.readthedocs.io/en/docs/
> Pin version of sphinx

- resqpy/grid/_face_functions.py
This patch adds a title to each grid connection set when it is constructed from a face set in the Grid class.
> gcs title now set when made from face set

- resqpy/multi_processing/wrappers/grid_surface_mp.py
- resqpy/olio/xml_et.py
This change largely restores Andy's versions of the two xml_et functions:
- match()
- list_obj_references()
whilst maintaining use of the LRU cache and empty list rather than None to terminate recursion in list_obj_references()
> fine tuning optimisation of olio.xml_et.match() and list_obj_references()

- resqpy/property/_collection_add_part.py
- resqpy/well/_blocked_well.py
This change removes the obtuse code for selecting between different blocked well initialisation methods and reverts to a much easier to understand if...elif sequence.
There is also a change to treat 'permeability length' and 'permeability thickness' as both okay when checking the property kind of a property with title 'KH'.
> Blocked well initialisation de-refactoring

- resqpy/model/_hdf5.py
- resqpy/model/_model.py
- resqpy/olio/write_hdf5.py
- resqpy/property/_collection_get_attributes.py
- resqpy/property/_property.py
- resqpy/property/property_collection.py
- tests/unit_tests/property/test_property.py
This change adds an option to pack bool arrays into bits (along the last axis) for hdf5 storage.  Note that using this option will generally result in non-resqpy applications not being able to read the array data for such properties.
> Support for packing and unpacking of bool array into bits for hdf5 storage

- resqpy/olio/xml_et.py
- tests/unit_tests/olio/test_xml_et.py
also fixing a bug in that function which was causing it to return prematurely if a maximum line count was not provided
> adding minimal test for olio.xml_et.print_xml_tree()

- resqpy/property/_collection_create_xml.py
- resqpy/surface/_mesh.py
- tests/unit_tests/unstructured/test_unstructured.py
Previously any non-standard uom would be added as extra metadata with Name 'uom'. This change brings resqpy in line with the RESQML technical reference by changing the Name to 'Uom'.
> using 'Uom' as extra metadata Name in line with technical reference

- resqpy/property/_collection_add_part.py
- resqpy/property/property_collection.py
- tests/unit_tests/property/test_property.py
This change adds a small piece of missing functionality – to reload a non standard unit of measure from extra metadata when it is present. A unit test for that situation is also added.
> reloading of extra metadata Uom when present

- resqpy/olio/transmission.py
- resqpy/organize/structural_organization_interpretation.py
- tests/integration_tests/test_grid_transmissibility_snapshots.py
The built in Darcy constant used by default for grid with xy & z units of metres was 100 times too great (yielding transmissibilities in m3.cP/(bar.d) instead of the m3.cP/(kPa.d) as stored in the extra metadata Uom field). This change corrects the Darcy constant to yield the correct transmissibilities in m3.cP/(kPa.d).
> correcting darcy constant in metric transmissibility formulation

- resqpy/derived_model/_add_faults.py
- resqpy/derived_model/_common.py
- resqpy/olio/grid_functions.py
- resqpy/property/_collection_create_xml.py
- resqpy/property/_collection_get_attributes.py
- resqpy/property/property_collection.py
- tests/unit_tests/derived_model/test_derived_model.py
- tests/unit_tests/fault/test_fault_connection_set.py
This change modifies the behaviour of the add_faults() function when a fault reaches the edge of the grid. The new code preserves the throw in that situation, rather than reducing to zero as happens at the end of fault within the grid.
There are also some minor enhancements to the inheritance of properties in the derived model functions.
> Derived model add_faults() enhancement

- resqpy/well/_blocked_well.py
- tests/unit_tests/well/test_blocked_well.py
This minor edit ensures the dtype of the original property array is maintained when adding property to blocked well from a grid. 
There is also an update to the unit tests for this code to add a continuous property, and check the dtype of one continuous and one discrete property are correct.
> Update _blocked_well.py to ensure dtype is maintained when adding grid property

- resqpy/property/_collection_add_part.py
- resqpy/property/property_collection.py
- resqpy/property/property_common.py
- tests/unit_tests/property/test_property.py
This change adds an optional _extra_ argument to the selective_version_of_collection() function, allowing extra metadata to play a role in property selection.
> extra metadata option for selective version of property collection

- resqpy/surface/_surface.py
- tests/unit_tests/surface/test_surface.py
New method on resqpy.surface.Surface to resample a Surface / triangulated set. Each existing triangle is split into 4 new triangles, with the edges defined by the mid-point of each original triangle edge.
Tests also included.
> resampling trianglulated surfaces

- resqpy/fault/_gcs_functions.py
- resqpy/grid/_grid.py
- resqpy/grid/_transmissibility.py
- resqpy/property/_collection_get_attributes.py
- tests/unit_tests/fault/test_fault_connection_set.py
- tests/unit_tests/property/test_property.py
This change adds support for directionally composite grid properties with indexable elements of 'faces', which is compatible with shape information given in RESQML documentation. (Till now, resqpy has worked with a direction facet for such properties – a mode which is still supported.)
> adding support for composite grid faces properties

- resqpy/grid_surface/_find_faces.py
- resqpy/multi_processing/wrappers/grid_surface_mp.py
- tests/unit_tests/multiprocessing/test_grid_surface_mp.py
- tests/unit_tests/test_grid_surface.py
This change adds an argument to the find_faces...regular() and ...optimised() functions that controls whether any agitation is random (as before) or constant (a small positive offset to x, y & z). The constant option can be useful for ensuring multiple coincident surfaces are gridded to the same faces. It also helps with reproducibility without having to use a random seed.
> adding argument to control random or non random agitation

- resqpy/well/_blocked_well.py
Update code to ensure that dtype of int64 is maintained where present while creating blocked well properties from grid cell properties.
> Update dtype to allow int64 when pulling from grid properties

- resqpy/well/_blocked_well.py
- tests/unit_tests/well/test_blocked_well.py
This change converts the units of measure of the LENGTH, RADW and RADB data to the requested length uom in the BlockedWell.dataframe() method. The change also affects the write_wellspec() method which calls the dataframe() method.
Resolves issue #747
> converting length, radw and radb properties to requested uom in BlockedWell.dataframe()

- resqpy/olio/vector_utilities.py
This change is to ensure that use of numba just in time compilation (njit) with the parallel option set true is thread safe.
> ruggedising njit parallel code

- resqpy/grid/_regular_grid.py
- resqpy/olio/load_data.py
- resqpy/property/_collection_create_xml.py
- resqpy/property/_collection_get_attributes.py
This patch updates numpy.product() calls with numpy.prod() due to deprecation of product().
> replacing deprecated numpy.product() with prod()

- resqpy/grid/_create_grid_xml.py
- resqpy/grid/_grid.py
- resqpy/grid/_grid_types.py
- resqpy/grid/_points_functions.py
- resqpy/grid/_write_hdf5_from_caches.py
- resqpy/olio/xml_et.py
- tests/unit_tests/grid/test_parametric_line_geometry.py
- tests/unit_tests/grid/test_points_functions.py
This change introduces support for the parametric line form of grid geometry. There are some restrictions:
- internal python representation is as before (convert on read and write)
- only a constant line kind index of 1 and knot count of 2 is supported (straight lines)
- horizontal or undefined parametric lines will raise an assertion error
- undefined topmost or basal cached points for any pillar will cause failure if writing in parametric line form
The code aims to be compatible with the geometry representation used by RMS when exporting to RESQML.
Resolves issue #723 
RMS is a trademark of AspenTech.
> handling of grid geometry stored in parametric line form

- resqpy/well/_deviation_survey.py
- resqpy/well/_trajectory.py
This patch decreases the priority of a deviation survey as the means to initialise a Trajectory. This allows another option to be used as the basis of the trajectory data whilst still setting up a related deviation survey.
> changing priority of Trajectory initialisation options

- resqpy/well/_trajectory.py
- tests/unit_tests/well/test_trajectory.py
This patch fixes a bug involving some old references to a root_node attribute in the Trajectory class when relating to a DeviationSurvey. The attribute has long since been replaced with a class property called root.
> old root_node references in Trajectory class updated

- resqpy/unstructured/_tetra_grid.py
- tests/unit_tests/unstructured/test_unstructured.py
This change introduces a TetraGrid method to determine the cell face handedness from the geometry. This initial implementation is not optimised for speed.
> initial functionality to determine face handedness for tetra grids

- resqpy/surface/_pointset.py
- tests/unit_tests/surface/test_surface_pointset.py
Enhances point set initialisation from an IRAP format ascii file to optionally (and by default) remove the last point if it is close to (999.0, 999.0, 999.0).
> Point set 999

- resqpy/rq_import/_add_surfaces.py
This change uses a shorter title when importing surfaces. The source file name is stored as an extra metadata item with key 'source'.
> using shorter title when importing surfaces

- .readthedocs.yaml
- docs/CONTRIBUTING.rst
I saw by email that our ReadtheDocs config format is deprecated, and the build is currently failing. This change should fix it. Link: <https://blog.readthedocs.com/migrate-configuration-v2/>
Example build now passes successfully: <https://readthedocs.org/projects/resqpy/builds/22562103/>
I also enabled the setting to build docs on all PRs. This may not take effect for this PR, but should work for future ones.
<https://docs.readthedocs.io/page/guides/autobuild-docs-for-pull-requests.html>
> Update Sphinx config to V2, and enable docs builds on PRs

- resqpy/well/_blocked_well.py
- tests/unit_tests/well/test_blocked_well.py
Aspen RMS is currently generating array data for blocked wells with incorrectly sized arrays. (Shared nodes incorrectly duplicated in nodes_md, or null values for inter-cell unblocked intervals omitted from grid indices.) This change is to allow resqpy to read such data. It is envisaged that the change will be removed once the code generating the malformed data is fixed.
RMS is a trademark of Roxar, part of AspenTech.
> temporary changes to blocked well load from xml to accommodate badly formed data

- resqpy/well/_blocked_well.py
- resqpy/well/_trajectory.py
- tests/unit_tests/well/test_blocked_well.py
- tests/unit_tests/well/test_trajectory.py
Enhance BlockedWell to allow splined trajectory to be built from numpy arrays of control points etc., rather than the inefficient and annoying pandas dataframe.
> Splined well interp

- resqpy/crs.py
- tests/unit_tests/test_crs.py
The Crs class is enhanced to handle conversions between crs'es with different axis orderings.
Unit tests for the crs module are also expanded.
> Crs handling conversion between different axis orderings

- resqpy/surface/__init__.py
- resqpy/surface/_tri_mesh.py
- tests/unit_tests/surface/test_tri_mesh.py
This patch handles a NaN z value in a tri mesh origin, simply replacing it with zero.
The surface module nan_removed_triangles_and_points() function is also added to the surface package init.
> nan z in tri mesh origin being set to zero

- resqpy/olio/vector_utilities.py
The olio.vector_utilities.points_in_triangles_njit() is returning some unexpected extra rows. This maybe an interference effect in a numba loop.
Attempting resolution by setting numba parallel explicitly False in olio.vector_utilities.points_in_triangles_njit()
> Issue with olio.vector_utilities.points_in_triangles_njit()

- resqpy/derived_model/_gather_ensemble.py
- resqpy/model/_forestry.py
- resqpy/olio/consolidation.py
- resqpy/organize/genetic_boundary_feature.py
- tests/unit_tests/conftest.py
- tests/unit_tests/derived_model/test_derived_model.py
- tests/unit_tests/lines/test_lines.py
- tests/unit_tests/surface/test_surface.py
- tests/unit_tests/time_series/test_time_series_functions.py
This patch fixes a bug whereby xml reference nodes to a string lookup were not being updated for categorical properties, in the derived_model.gather_ensemble() function.
Resolves issue #775
> fix of bug affecting StringTableLookup references in xml in derived_model.gather_ensemble()

- resqpy/grid_surface/grid_surface_cuda.py
- resqpy/well/_blocked_well.py
- tests/unit_tests/conftest.py
- tests/unit_tests/fault/test_fault_connection_set.py
- tests/unit_tests/grid/conftest.py
- tests/unit_tests/model/test_model.py
- tests/unit_tests/olio/test_write_hdf5.py
- tests/unit_tests/property/test_property.py
- tests/unit_tests/rq_import/test_rq_import.py
- tests/unit_tests/well/test_blocked_well.py
- tests/unit_tests/well/test_wellbore_marker_frame.py
Adjusting unit tests so they don't generate warnings:
- removing instances of abstract 'discrete' and 'continuous' as property kind
- floating point underflow when testing writing floating point data to hdf5 at reduced precision
> cleaniing up unit test warnings

- resqpy/derived_model/_gather_ensemble.py
- tests/unit_tests/derived_model/test_derived_model.py
Similar to the recent changes for string lookup references, this change ensures references to local property kinds are correctly handled during consolidation in ensemble gathering.
> ensuring local property kind references are handled correctly during ensemble gathering

- resqpy/multi_processing/wrappers/grid_surface_mp.py
- resqpy/olio/triangulation.py
- resqpy/surface/_surface.py
- tests/unit_tests/olio/test_triangulation.py
- tests/unit_tests/surface/test_surface.py
The old saucer option for surface flange extension uses a complex computation designed to follow local rim curvature in the original surface when extending. This change adds a much simpler option, activated when the saucer parameter is outside the range 0.0 to 1.0 (but between -90.0 and 90.0). In that case the parameter is interpreted as a flange angle (off the average plane of the surface).
> simple saucer flange extension option

- resqpy/multi_processing/wrappers/grid_surface_mp.py
- tests/unit_tests/multiprocessing/test_grid_surface_mp.py
When gridding surfaces to a regular grid using the multi processing wrapper, this change adds a new argument, flange_radius, and reduces the radial factor.
> exposing flange radius control in grid surface mp wrapper

- resqpy/surface/_surface.py
- tests/unit_tests/surface/test_surface.py
Delauney triangulation fails if there are any not-a-number (NaN) values present amongst the points. This patch removes such points and gives a warning prior to triangulating a Surface from a PointSet.
> removing not-a-number points from point set prior to triangulation

- resqpy/lines/_polyline.py
- tests/unit_tests/lines/test_lines.py
This change makes the Polyline interpolated_point() function more robust against rounding errors when f = 1.0
> Polyline interpolated point function ruggedised against rounding error

- resqpy/weights_and_measures/weights_and_measures.py
- tests/unit_tests/surface/test_surface.py
- tests/unit_tests/test_weights_measures.py
This patch adds ftUS as an alias for RESQML length unit of measure ft[US].
> adding ftUS as alias for tf[US]

- resqpy/surface/_tri_mesh.py
- tests/unit_tests/surface/test_tri_mesh.py
> passing extra metadata to TriMesh.from_tri_mesh_and_z_values()

- resqpy/surface/_surface.py
- tests/unit_tests/surface/test_surface.py
Adds an edge_lengths() method to the Surface class, returning the lengths of the triangle edges.
> adding Surface.edge_lengths() method

- resqpy/surface/_surface.py
Fixing bug affecting dtype of triangles array when resampling (refining) Surface.
Also sets Surface triangles and points attributes when setting from triangles and points.
> bug fix in surface resampling and pre setting triangles and points

- resqpy/time_series/_any_time_series.py
- resqpy/time_series/_geologic_time_series.py
- tests/unit_tests/time_series/test_any_time_series.py
- tests/unit_tests/time_series/test_time_series_functions.py
This change is functionally equivalent to #797, to allow test pipeline to run. The change allows the year offset in the timestamps of geological time series to be zero.
> Accepting YearOffset of zero for geologic time series; replaces PR #797

- resqpy/surface/_surface.py
- tests/unit_tests/surface/test_surface.py
This patch stores (and reloads) a Surface normal vector if it has been established at the time of the create_xml() call. (The normal vector can be established by calling the Surface.normal() method, which caches the result as the normal_vector attribute.)
> Storing surface normal vector as extra metadata (if established at time of create_xml)

- resqpy/property/_collection_create_xml.py
- resqpy/property/property_common.py
- tests/unit_tests/property/test_property.py
This change resolves issue #802 
Note that the resqpy.property.supported_property_kind_list is maintained for backward compatibility but it is preferable for calling code to use the underlying function instead: resqpy.weights_and_measures.valid_property_kinds(), which returns a set.
> using weights and measures valid property kinds as supported property kind list

- resqpy/property/attribute_property_set.py
- tests/unit_tests/property/test_attribute_property_set.py
This change improves the handling of key clashes in the AttributePropertySet class.
> AttributePropertySet improvements

- resqpy/well/_blocked_well.py
- tests/unit_tests/well/test_blocked_well.py
This change resolves issue #813
> supporting time dependent blocked well connection open property

- resqpy/model/_hdf5.py
- resqpy/model/_model.py
- tests/unit_tests/model/test_model.py
This change adds a method to the Model class for overwriting an entire hdf5 array. (There was already a method for overwriting a slice of an array.)
> whole array overwrite method in Model

- resqpy/grid_surface/_find_faces.py
- resqpy/multi_processing/wrappers/grid_surface_mp.py
This patch stores the surface extrapolation flange property in numpy.uint8 dtype.
> saving surface extrapolation flange property as np.unit8 dtype

- resqpy/fault/_grid_connection_set.py
- tests/unit_tests/fault/test_fault_connection_set.py
When active_only option is in use, the fip array needs to be masked alongside cip. This is a bug fix.
> masking fip array in GridConnectionSet.grid_face_arrays()

- resqpy/surface/_surface.py
Handle double spaces in tsurf format import - previously if double-spaces were present rather than single spaces (as in some .ts files) the import would fail
> Handle double spaces in .ts formatted tset file import

- tests/unit_tests/grid/test_regular_grid.py
- tests/unit_tests/olio/test_write_hdf5.py
The np.product() synonym has been dropped from more recent versions of numpy.
> replacing np.product() with np.prod() in unit tests

- resqpy/multi_processing/wrappers/grid_surface_mp.py
- resqpy/olio/write_hdf5.py
- resqpy/property/_collection_add_part.py
- resqpy/property/_collection_create_xml.py
- resqpy/property/property_collection.py
Following on from support for generating grid bisectors in a packed form (in find_faces..), this change adds support for the pre-packed arrays in the PropertyCollection imported list, and in the multiprocessing wrapper for find faces.
> handling pre-packed arrays in property collection

- resqpy/grid_surface/_find_faces.py
- resqpy/multi_processing/wrappers/grid_surface_mp.py
The find faces wrapper was using the use_pack argument to indicate the pre-packed state when adding every bisector array to the property collection. However, curtain bisectors are always returned in an unpacked form. This change fixes this bug.
> setting pre packed False for curtains in find faces wrapper

- resqpy/grid/_extract_functions.py
- resqpy/grid/_grid.py
- tests/unit_tests/grid/test_xyz.py
This change enhances the Grid class with:
- a frontier() method which generates a frontier polygon for the edge of the grid
- option to not load the inactive mask attribute when opening an existing grid
> Grid frontier polygon method

- resqpy/grid/_grid.py
- tests/unit_tests/grid/test_xyz.py
This change enhances the functionality of the Grid.frontier() method by adding a mode argument, which may be one of:
- 'mean'
- 'top'
- 'base'
- 'inner'
- 'outer'
> adding mode argument to Grid.frontier() method

- resqpy/multi_processing/wrappers/grid_surface_mp.py
Exposes the reorient argument (previously True) to allow user definition. Still defaults to True when not provided.
> Update grid_surface_mp.py to expose reorient argument

- .github/codecov.yml
- .github/workflows/ci-tests.yml
Temporarily making Codecov okay to fail in test pipeline, until token issue resolved.
> Codecov off

- .github/codecov.yml
- .github/workflows/ci-tests.yml
- resqpy/time_series/_any_time_series.py
- tests/unit_tests/time_series/test_any_time_series.py
Allow the YearOffset to be zero in TimeSeries with a "human" timescale. Have encountered examples of this, and it seems a reasonable thing to allow.
> Allow 0 YearOffset elements for 'human' timescales

- .github/actions/prepare-poetry/action.yml
- .github/codecov.yml
- .github/workflows/ci-tests.yml
- .github/workflows/codeql-analysis.yml
Fix the codecov action by bumping the version, and updating the repo upload token.
Reset `fail_ci_if_error: true`.
Also bump outdated `upload-artifact`, `cache` and `setup-python` actions.
> MAINT: Fix codecov upload, bump github action tags

- resqpy/multi_processing/wrappers/grid_surface_mp.py
- resqpy/olio/triangulation.py
- resqpy/surface/_surface.py
- tests/unit_tests/olio/test_triangulation.py
- tests/unit_tests/surface/test_surface.py
These changes revert previous changes using the non-triangulation method when a saucer is required, but reorient is False. Instead the set_from_point_set method can now handle saucers without reorientation.
These changes mean that when a flange points are being added, but reorientation is False, the flange points are still generated and added based on the reoriented points (to the normal vector orientation), however the triangulation is completed in non-reoriented space
> Updates to ensure reorientation before flange point generation, even where triangulation is completed in non-reoriented space

- resqpy/model/_forestry.py
- resqpy/multi_processing/wrappers/grid_surface_mp.py
- resqpy/surface/_surface.py
- tests/unit_tests/model/test_model.py
This patch fixes a bug affecting uuid changes in reference nodes during consolidation when more than one reference node within an object refers to the same target referenced object. The bug shows up, for example, if copying a multi-patch Surface and an equivalent Crs already exists with a different uuid in the target model.
> fixing bug affecting crs uuid references in surface patches during consolidation

- resqpy/grid_surface/__init__.py
- resqpy/grid_surface/_find_faces.py
- resqpy/model/_model.py
- resqpy/multi_processing/wrappers/grid_surface_mp.py
- resqpy/property/property_collection.py
- resqpy/surface/_surface.py
- tests/unit_tests/test_grid_surface.py
This optimisation reduces the search volume when creating a composite bisector for a patchwork horizon.
> patch boxes during bisector generation

- resqpy/rq_import/_add_surfaces.py
- tests/unit_tests/rq_import/test_rq_import.py
Update to allow the required "interpretation_type" (horizon, fault, geobody) when importing using "add_surface" and adding features and interpretations. If horizon is selected (default) then GeneticBoundaryFeature and HorizonInterpretation is added, if fault is selected then TectonicBoundaryFeature and FaultInterpretation is added, if geobody is selected then GeobodyFeature and GeobodyInterpretation is added.
> Enhancement to _add_surfaces.py to allow for fault and geobody types on import

- resqpy/grid_surface/_find_faces.py
- tests/unit_tests/surface/test_surface.py
This change modifies the find faces... functionality for patchwork surfaces when called with a patch indices array for the grid cells. In that case, the function now only includes faces where the related triangle patch matches that of one of the two grid cells which adjoin the face. (Previously all faces for all the surface patches were included without filtering.)
> patchwork grid connection set for filtered faces only

- resqpy/surface/_tri_mesh.py
- tests/unit_tests/surface/test_tri_mesh.py
Adds an area() method to the TriMesh class, returning an approximate area based on the proportion of non-NaN z values.
> Tri mesh area method
